services:
  # default configuration for services in *this* file
  _defaults:
    autowire: true      # Automatically injects dependencies in your services.
    autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.
    public: false

  # Cache interface configuration
  Psr\SimpleCache\CacheInterface:
    alias: cache.app

  # Configuration class
  WechatMiniProgramTrackingBundle\Config\TrackingConfig:
    arguments:
      $notFoundFallbackPage: '%env(default::null:WECHAT_MINI_PROGRAM_NOT_FOUND_FALLBACK_PAGE)%'

  WechatMiniProgramTrackingBundle\Controller\:
    resource: '../../Controller/'
  WechatMiniProgramTrackingBundle\Repository\:
    resource: '../../Repository/'
  WechatMiniProgramTrackingBundle\Service\:
    resource: '../../Service/'
    public: true
  WechatMiniProgramTrackingBundle\Procedure\:
    resource: '../../Procedure/'
  WechatMiniProgramTrackingBundle\Logger\:
    resource: '../../Logger/'
  WechatMiniProgramTrackingBundle\Command\:
    resource: '../../Command/'